### PR TITLE
fix(modal): make header close button optional

### PR DESCRIPTION
**Pull request by AlasdairSwan**
More modal tweaks.

### CODE REVIEW

**Comment by fysheets** [comment]
Two comments regarding focus management:
1. When you open this Modal in storybook the focus doesn't go anywhere anymore (I think I'd expect it on the close button at the bottom)
2. When you try to tab through the Modal now the following console error appears because it's trying to focus on the hidden button:
screen shot 2018-04-18 at 9 50 26 am

**Comment by AlasdairSwan** [comment]
Damn, that head close button is very useful for focus management.

**Comment by fysheets** [comment]
@AlasdairSwan that works for me -- I did a quick check with your previous commit for the focus errors and saw that they were gone & it worked as expected. Thanks for the clarification on focus going to the Modal itself :)

**Comment by AlasdairSwan** [comment]
@fysheets I updated the Sass to add indication of focus to the modal. If you could take another look that would be great.

**Comment by AlasdairSwan** [comment]
@jaebradley I addressed your comments too.

**Pull request merged**
