### PR TITLE
[BD-35] PAR-288 feat: update styles for tabs component according to new design

### PR DESCRIPTION
**Pull request by amalbas**
Ticket on jira: https://openedx.atlassian.net/browse/PAR-288
Update styles for tabs component according to new design
tabs-new

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @amalbas! I've created [BLENDED-802](https://openedx.atlassian.net/browse/BLENDED-802) to keep track of it in Jira.


When this pull request is ready, tag your edX technical lead.

**Review by abutterworth — CHANGES_REQUESTED** [review]
The edges of the bottom border are at an angle. Is there a way to keep them square? 
image

**Comment by amalbas** [comment]
@abutterworth I fixed the angle border.

**Review by abutterworth — CHANGES_REQUESTED** [review]
The bottom border should be inline with the "tab set"'s bottom border. Screenshot from the PR: 
image 
vs the design:
image

Also, the transition animation for the border is causing jitters when switching tabs.

Is it possible to address these issues without reworking the javascript component itself?

**Pull request closed without merging**
