### PR TITLE
Using action instead of console.log in checkbox story

### PR DESCRIPTION
**Pull request by kgroat**
This was using `console.log`, but I noticed that you already had `addon-actions` enabled, so it seemed like this was the better approach.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @kgroat! I've created [OSPR-1969](https://openedx.atlassian.net/browse/OSPR-1969) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/paragon/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by arizzitano** [comment]
Hey good catch @kgroat, thanks for the fix! The code looks good to me, so we should be good to start getting this merged once we get your signed contributor agreement ([instructions here](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst#step-1-sign-a-contribution-agreement)). Just out of curiosity, how did you find Paragon?

**Comment by nedbat** [comment]
@kgroat Are you interested in continuing with this contribution?

**Comment by nedbat** [comment]
@kgroat I'm going to go ahead and close this pull request.  When you come back to it, feel free to re-open it.  Thanks again.

**Comment by edx-webhook** [comment]
@kgroat Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/paragon&entry.867055334=https://github.com/edx/paragon/pull/49&entry.1484655318=https://github.com/kgroat&entry.752974735=2017-10-15+05:25&entry.1917517419=2017-11-30+20:53&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
